### ISSUE TITLE
Looks like a promising plugin

### ISSUE THREAD

**Issue by MikeiLL** [Ramoonus/Powerpack#81]
Are you planning to enable administrators to target specific DOM elements for libraries via the GUI interface?

Or is this simply for adding the libraries?

For example I am thinking of using `lettering.js`. Would the idea be to call the function from within the theme code?

**Comment by Ramoonus** [comment]
hello Mike
im aiming to make shortcodes, but no GUI to target dom elements

**Comment by MikeiLL** [comment]
I would love to see a description of your vision for the plugin and it's usage.
